### ISSUE TITLE
Fix UI

### ISSUE THREAD

**Issue by squilter** [DroidPlanner/dp-pebble#1]
The android app should have two buttons:
- The first links to 3dr-services on the play store.  If 3dr-services is already installed, that button is grayed out.  
- The second button should bring up a dialog box to install/update the watchapp.  The dialog box asks if the user wants to install the app via "pebble store (recommended)" or via "offline install".  If the pebble isn't connected, this should be grayed out.

**Comment by m4gr3d** [comment]
@squilter the first button is not really needed. To use 3dr services, you use the client library. Once it's invoked, that library checks if 3dr services is installed and prompt the user via a dialog to install it if it's not.

You can check the behavior by uninstalling 3dr services and starting DP3 .

**Comment by squilter** [comment]
Thanks
