### ISSUE TITLE
Clicking pause sometimes changes to "guided"

### ISSUE THREAD

**Issue by squilter** [DroidPlanner/dp-pebble#14]
Clicking `pause` should change to `guided::pause` but instead just changes to `guided`.  Not sure if it isn't changing the mode properly after clicking pause, or if the app isn't parsing the mode properly.

**Comment by squilter** [comment]
@ne0fhyk I have a suspicion that this bug might be in 3DR-Services.  Here's a brief explanation:

Step 1:  Call [`drone.pauseAtCurrentLocation();`
](https://github.com/DroidPlanner/dp-pebble/blob/master/Android/src/main/java/org/droidplanner/pebble/PebbleCommunicatorService.java#L308)

Step 2: Get [`drone.getAttribute(AttributeType.GUIDED_STATE).isIdle();`](https://github.com/DroidPlanner/dp-pebble/blob/master/Android/src/main/java/org/droidplanner/pebble/PebbleCommunicatorService.java#L228)

Expected outcome is that the mode changes to guided and that the second call starts returning true.  That usually happens.  But sometime the mode changes to guided but the second call continues returning false.

**Comment by m4gr3d** [comment]
@squilter found and fixed the issue. It should be in version `1.2.5.beta`.

**Comment by squilter** [comment]
Great, Thanks!
