### ISSUE TITLE
Integrate with 3dr-services

### ISSUE THREAD

**Issue by squilter** [DroidPlanner/dp-pebble#2]
properly forward the telemetry to the pebble, and forward the commands to the vehicle.

**Comment by squilter** [comment]
@ne0fhyk Do I need to call `drone.connect(connParams);`?  

I was hoping that I could just wait for the user to connect using an app like droidplanner, and then just start sending and receiving data.

**Comment by m4gr3d** [comment]
@squilter for the current version of 3dr services, you do need to explicitly connect. 
I'm brainstorming an option to alert listeners of successful vehicle connection that would permit the use case you're thinking off, although it might take me some time to implement it.

For the moment, you could let the connection be done from the android app, and switch to listener mode when it's implemented in 3dr services.

By the way, feel free to add a ticket for that feature on the 3dr services issues list, as well as any other ideas, or issues you ran into when using the current api.

**Comment by squilter** [comment]
When I connect using DroidPlanner and then connect again using dp-pebble, will it connect to the same vehicle without conflict?

**Comment by m4gr3d** [comment]
yes, it's designed to do so. I've been using/testing multiple apps connected to the same vehicle through 3dr services.

In the screenshot below, both apps are connected to the same vehicle (sitl):

![multi_app_3dr_services](https://cloud.githubusercontent.com/assets/914968/5696950/4e0487f0-9997-11e4-926b-f0a03b5bd053.png)

**Comment by squilter** [comment]
Issue "fixed" with 073c9284868eb234833e59d491503c4f1649fdc8.  It just connects assuming standard parameters (usb, 57600 baud).  I will redo this once 3dr-services allows me to connect to an existing connection.
