### ISSUE TITLE
Check if service should be running on activity start

### ISSUE THREAD

**Issue by squilter** [DroidPlanner/dp-pebble#26]
In case the `ACTION_VEHICLE_CONNECTION` doesn't start the service properly, the user will probably open the android app to see if something is wrong.  Opening the android app should make sure that the service is running if it's supposed to be.  See example [here](https://github.com/DroidPlanner/tower-wear/blob/fc2c77f019a1dbcc0df357d00f3bdb2a5169a2f1/mobile/src/main/java/com/o3dr/android/dp/wear/services/DroneService.java#L135)

Maybe not necessary if it seems to connect/disconnect very reliably.

**Comment by m4gr3d** [comment]
@squilter Should be fixed by PR #29. I don't have a pebble at the moment, so could you give a test to make sure i didn't introduce any bugs.

This issue can be tested by installing the app after Tower is connected, and seeing if it correctly picks up the already existing connection.

**Comment by squilter** [comment]
fixed by #29
