### ISSUE TITLE
Update to latest dronekit-android client library

### ISSUE THREAD

**Issue by m4gr3d** [DroidPlanner/dp-pebble#32]
@squilter The latest client library revamps the error handling logic, and add a new follow me mode ('Look-At-Me').

The docs are still being updated, but you can include support by replacing the current compile dependency with:
`compile 'com.o3dr.android:dronekit-android:2.3.11'`

**Comment by squilter** [comment]
@ne0fhyk Done.  Do I need to make any other changes with that, or should I just make a new release?

**Comment by m4gr3d** [comment]
No additional changes is needed besides testing to make sure no bugs was
introduced. Once that's done, then you can push a new release.

## 

Fredia Huya-Kouadio
Senior Android Engineer, 3D Robotics
fredia@3dr.com
