### ISSUE TITLE
Doesn't work on pebble time

### ISSUE THREAD

**Issue by HuguesD** [DroidPlanner/dp-pebble#33]
Hi,
I installed tower on latest android phone. I also installed the tower pebble app on the phone. 
Nothing happens on the pebble watch. How does it work ?

**Comment by squilter** [comment]
Thanks for the report.  I don't have a pebble time, and I'm not surprised that it doesn't work out of the box.

**Comment by HuguesD** [comment]
Does it mean that the tower pebble only works on previous pebble and not on the latest time version ?
or is the tower pebble app just broken ?
Did anyone already used it once ?

**Comment by squilter** [comment]
Yes, it works fine on the original pebble.

**Comment by HuguesD** [comment]
Ok good to know. Can you describe the installation & configuration steps you follow to make it work on the original pebble ? Maybe I'm not doing something needed and I do not understand the link between the pebble watch and Tower : do you need to install something on the pebble watch ?

**Comment by squilter** [comment]
On Android you need 3DR Services and Tower Pebble.  You can also install Tower, but it isn't necessary.  After that, open Tower Pebble and click the install button to install the watchapp on the pebble.

**Comment by hamishwillee** [comment]
@n0k This is probably something we need to include in the Android docs.

**Comment by HuguesD** [comment]
The procedure works now. Thx.
Is there a document describong the functions available from the pebble watch screen ? I xurrently see only one screen, that shows three buttons : follow, pause, RTL and a connection status indication. Are there other functions ?

**Comment by squilter** [comment]
No, that's all there is.

**Comment by HuguesD** [comment]
Ok. For fun (I am sure there are better ways to do this) I am developing/playing with a pebbel time watch on which I am running a HTTP rest client. The client will connect to a ESP8266 Wifi/UART device (running its own web server and waiting for a http get from the watch). Then in turn the ESP8266 converts the HTTP GET (requesting a "RTL" for exampl) to its UART interface which is connected via USB (USB/UART FTDI) to a GCS. The GCS then sends the command to the multicopter via mavlink (using dronekit.io). I am at step where I send the requested action to the UART interface. I still have to develop the GCS part with dronekit.io.
Maybe this could be a way to extend the use of more complex APM:Copter control from a pebble watch ?
Let me know what you think.

**Comment by squilter** [comment]
I saw your work on DIYDrones.  Looks cool!

**Comment by HuguesD** [comment]
Thx Squilter, it was indeed a fun learning project to do. As I posted as a comment, you should upgrade the current Tower Pebble app to use the color screen of the last Pebble watches.
